// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Relos.DataService;

#nullable disable

namespace Relos.DataService.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Relos.Models.DatabaseModels.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArchivedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ArchivedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ContactId")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<int>("LastUpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryNumber")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryNumber")
                        .HasColumnType("text");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedByUserId");

                    b.HasIndex("ContactId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Relos.Models.DatabaseModels.CustomContactFieldTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArchivedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ArchivedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ContactFieldType")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<int>("LastUpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("CustomContactFieldTemplate");
                });

            modelBuilder.Entity("Relos.Models.DatabaseModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedBySystemUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedBySystemUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLoginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdatedBySystemUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Relos.Models.DatabaseModels.UserOauthAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArchivedBySystemUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AuthProvider")
                        .HasColumnType("integer");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedBySystemUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedBySystemUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserOauthAccounts");
                });

            modelBuilder.Entity("Relos.Models.DatabaseModels.Workspace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArchivedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ArchivedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<int>("LastUpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkspaceDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkspaceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WorkspaceOwnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArchivedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LastUpdatedByUserId");

                    b.HasIndex("WorkspaceOwnerId");

                    b.ToTable("Workspaces");
                });

            modelBuilder.Entity("Relos.Models.DatabaseModels.Contact", b =>
                {
                    b.HasOne("Relos.Models.DatabaseModels.User", "ArchivedByUser")
                        .WithMany()
                        .HasForeignKey("ArchivedByUserId");

                    b.HasOne("Relos.Models.DatabaseModels.Contact", null)
                        .WithMany("Contacts")
                        .HasForeignKey("ContactId");

                    b.HasOne("Relos.Models.DatabaseModels.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relos.Models.DatabaseModels.User", "LastUpdatedByUser")
                        .WithMany()
                        .HasForeignKey("LastUpdatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relos.Models.DatabaseModels.Workspace", "Workspace")
                        .WithMany("Contacts")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchivedByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastUpdatedByUser");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Relos.Models.DatabaseModels.CustomContactFieldTemplate", b =>
                {
                    b.HasOne("Relos.Models.DatabaseModels.User", "ArchivedByUser")
                        .WithMany()
                        .HasForeignKey("ArchivedByUserId");

                    b.HasOne("Relos.Models.DatabaseModels.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relos.Models.DatabaseModels.User", "LastUpdatedByUser")
                        .WithMany()
                        .HasForeignKey("LastUpdatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relos.Models.DatabaseModels.Workspace", "Workspace")
                        .WithMany("CustomContactFieldTemplates")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchivedByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastUpdatedByUser");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Relos.Models.DatabaseModels.UserOauthAccount", b =>
                {
                    b.HasOne("Relos.Models.DatabaseModels.User", "User")
                        .WithOne("UserOauthAccount")
                        .HasForeignKey("Relos.Models.DatabaseModels.UserOauthAccount", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Relos.Models.DatabaseModels.Workspace", b =>
                {
                    b.HasOne("Relos.Models.DatabaseModels.User", "ArchivedByUser")
                        .WithMany()
                        .HasForeignKey("ArchivedByUserId");

                    b.HasOne("Relos.Models.DatabaseModels.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relos.Models.DatabaseModels.User", "LastUpdatedByUser")
                        .WithMany()
                        .HasForeignKey("LastUpdatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relos.Models.DatabaseModels.User", "WorkspaceOwner")
                        .WithMany()
                        .HasForeignKey("WorkspaceOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchivedByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("LastUpdatedByUser");

                    b.Navigation("WorkspaceOwner");
                });

            modelBuilder.Entity("Relos.Models.DatabaseModels.Contact", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("Relos.Models.DatabaseModels.User", b =>
                {
                    b.Navigation("UserOauthAccount")
                        .IsRequired();
                });

            modelBuilder.Entity("Relos.Models.DatabaseModels.Workspace", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("CustomContactFieldTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
